package com.serverless.model;

import com.amazonaws.services.dynamodbv2.AmazonDynamoDB;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDB;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperConfig;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.serverless.util.DynamoDBAdapter;

@DynamoDBTable(tableName = "Car")
public class Car {

	private String id;
	private String licensePlateNumber;
	private String groupName;
	private String modelName; 
	private String deviceId;
	
	public static final  DynamoDBMapper dynamoDBMapper;
	public static final AmazonDynamoDB dynamoDBClient;
	private static final String carTableName = System.getenv("CAR_TABLE_NAME");
	
	/**
	 * initialiing dynamo db client and mapper
	 */
	static {
		DynamoDBAdapter dynamoDBAdapter = DynamoDBAdapter.getInstance();
		DynamoDBMapperConfig mapperConfig = DynamoDBMapperConfig.builder()
											.withTableNameOverride(new DynamoDBMapperConfig.TableNameOverride(carTableName))
											.build();
		
		dynamoDBMapper = dynamoDBAdapter.getDbMapper(mapperConfig);
		dynamoDBClient = dynamoDBAdapter.getDbClient();
	}
	
	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	
	@DynamoDBAttribute(attributeName = "license_plate_number")
	public String getLicensePlateNumber() {
		return licensePlateNumber;
	}
	public void setLicensePlateNumber(String licensePlateNumber) {
		this.licensePlateNumber = licensePlateNumber;
	}
	
	@DynamoDBAttribute(attributeName = "group_name")
	public String getGroupName() {
		return groupName;
	}
	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}
	
	@DynamoDBAttribute(attributeName = "model_name")
	public String getModelName() {
		return modelName;
	}
	public void setModelName(String modelName) {
		this.modelName = modelName;
	}
	
	@DynamoDBAttribute(attributeName = "device_id")
	public String getDeviceId() {
		return deviceId;
	}
	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}
	
	
}
